version: '3.8'
services:
  backend:
    build: ./todo-backend
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./todo-frontend
      args:
        VITE_BACKEND_URL: "http://backend:3001"
    ports:
      - "5173:80"
    depends_on:
      - backend
