services:
  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend-prod

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: todo-backend-prod
    environment:
      - PORT=3001
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: todo-mongo
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: todo-redis

  nginx:
    image: nginx:alpine
    container_name: reverse-proxy-prod
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data: