services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-prod

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    container_name: backend-prod

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    container_name: reverse-proxy-prod
