# Use official Node.js base image
FROM node:18

# Create and set app directory
WORKDIR /usr/src/app

# Copy the JavaScript file
COPY index.js .

# Run the script when the container starts
CMD ["node", "index.js"]
